package main

import (
	_ "github.com/FirasYousfi/tasks-web-servcie/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/gorilla/mux"
	"github.com/rs/zerolog/log"
	httpSwagger "github.com/swaggo/http-swagger"
	"net/http"
)

func main() {
	r := mux.NewRouter()
	r.PathPrefix("/swagger/").Handler(httpSwagger.Handler(
		httpSwagger.URL("/swagger/doc.json"),
	)).Methods(http.MethodGet)

	log.Info().Msg("swagger server listening on port 8080, check 'http://localhost:8080/swagger/doc.json' for the docs")
	log.Info().Msg("check 'http://localhost:5000/swagger/index.html' for the UI")

	log.Fatal().Err(http.ListenAndServe(":5000", r))
}
