apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task-service-app.fullname" . }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.config.database.user | b64enc | quote }}
  POSTGRES_PASSWORD:  {{ .Values.config.database.password | b64enc | quote }}