apiVersion: v1
kind: Service
metadata:
  name: {{ include "task-service-app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "task-service-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }} ## service port
      targetPort: http  # container port should match port in deployment, this is the port we will forward requests to so it is the one the app is listening on. Refers directly with name to the one in deployment.
      protocol: TCP
  selector:
    {{- include "task-service-app.selectorLabels" . | nindent 4 }} ## should be the same as labels in deployment
